# Generated by Django 3.2.9 on 2021-11-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('major', models.CharField(max_length=40)),
                ('academic_year', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
