# Generated by Django 3.2.9 on 2021-11-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(blank=True, choices=[('FIRST', 1), ('SECOND', 2), ('THIRD', 3), ('FOURTH', 4), ('FIFTH', 5), ('SIXTH', 6), ('SEVENTH', 7)]),
        ),
    ]
