# Generated by Django 3.2.9 on 2021-11-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='payment_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('fawry', 'Fawry'), ('visa', 'Visa')], default='telegram', max_length=20),
        ),
    ]
