# Generated by Django 3.2.9 on 2021-11-19 18:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0002_auto_20211119_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('owner', 'name')},
        ),
    ]
