# Generated by Django 3.2.9 on 2021-11-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20211124_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'verbose_name_plural': 'Watch history'},
        ),
    ]
