# Generated by Django 3.2.9 on 2022-02-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('telegram_username', models.CharField(max_length=100)),
                ('messenger_username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
