# Generated by Django 3.2.9 on 2022-02-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(default='', upload_to='categories/icons'),
            preserve_default=False,
        ),
    ]
