# Generated by Django 3.2.9 on 2021-11-22 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='comments',
            field=models.ManyToManyField(blank=True, to='courses.Comment'),
        ),
        migrations.AddField(
            model_name='course',
            name='comments',
            field=models.ManyToManyField(blank=True, to='courses.Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
    ]
