# Generated by Django 3.2.9 on 2021-11-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(default='f', max_length=50),
            preserve_default=False,
        ),
    ]
