# Generated by Django 3.2.9 on 2021-11-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211122_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='course',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.content'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.course'),
            preserve_default=False,
        ),
    ]
