# Generated by Django 3.2.9 on 2021-11-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_quiz_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.quiz'),
        ),
        migrations.AlterField(
            model_name='course',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.quiz'),
        ),
    ]
