# Generated by Django 3.2.9 on 2021-11-25 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_feedback_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseProgress',
            new_name='CourseActivity',
        ),
    ]
