# Generated by Django 3.2.9 on 2022-03-30 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseactivity_left_off_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseactivity',
            name='left_off_at',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
