# Generated by Django 3.2.9 on 2021-11-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211114_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'verbose_name_plural': 'course progress'},
        ),
    ]
