# Generated by Django 3.2.9 on 2021-11-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211122_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=100),
        ),
    ]
