# Generated by Django 3.2.9 on 2021-11-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211120_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_name',
            new_name='name',
        ),
    ]
