# Generated by Django 3.2.9 on 2021-11-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211127_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='is_correct',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
