# Generated by Django 3.2.9 on 2021-11-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseprogress_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='content',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('order',)},
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
