# Generated by Django 3.2.9 on 2021-11-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_quizresult_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
