# Generated by Django 3.2.9 on 2022-01-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_quizresult_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachement',
            name='file',
            field=models.FileField(upload_to='attachements'),
        ),
        migrations.AlterField(
            model_name='content',
            name='audio_content',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_content',
            field=models.FileField(upload_to='video'),
        ),
    ]
