# Generated by Django 3.2.9 on 2022-01-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220112_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='audio_content',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_content',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
