# Generated by Django 3.2.9 on 2022-01-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220112_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='audio_content',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='text_content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='video_content',
            new_name='video',
        ),
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
