# Generated by Django 3.2.9 on 2022-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220117_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
