# Generated by Django 3.2.9 on 2022-01-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachement',
            name='title',
            field=models.CharField(default='Attachement', max_length=100),
            preserve_default=False,
        ),
    ]
