# Generated by Django 3.2.9 on 2022-01-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_attachement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
