# Generated by Django 3.2.9 on 2022-01-21 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_alter_question_question_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_activity', to=settings.AUTH_USER_MODEL),
        ),
    ]
