# Generated by Django 3.2.9 on 2022-01-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_content_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
