# Generated by Django 3.2.9 on 2022-01-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_content_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
