# Generated by Django 3.2.9 on 2022-01-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_courseactivity_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseactivity',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='courses.content'),
        ),
    ]
