# Generated by Django 3.2.9 on 2022-01-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_courseactivity_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='courses.quiz'),
        ),
    ]
