# Generated by Django 3.2.9 on 2022-01-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_content_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
