# Generated by Django 3.2.9 on 2022-01-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_content_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
