# Generated by Django 3.2.9 on 2022-02-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_topic_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='course',
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='courses.topic'),
            preserve_default=False,
        ),
    ]
