# Generated by Django 3.2.9 on 2022-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_content_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
