# Generated by Django 3.2.9 on 2022-02-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20220225_1946'),
        ('courses', '0021_auto_20220220_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='categories.Tag'),
        ),
    ]
