# Generated by Django 3.2.9 on 2022-04-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregatecard',
            old_name='model',
            new_name='model_type',
        ),
    ]
