# Generated by Django 3.2.9 on 2022-04-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0003_auto_20220415_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AggregateCondition',
        ),
        migrations.RenameField(
            model_name='aggregatecard',
            old_name='conditions',
            new_name='filters',
        ),
    ]
