# Generated by Django 3.2.9 on 2022-04-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0004_auto_20220415_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatecard',
            name='filters',
        ),
        migrations.AddField(
            model_name='aggregatefilter',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='admin_analytics.aggregatecard'),
            preserve_default=False,
        ),
    ]
