# Generated by Django 3.2.9 on 2022-04-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0006_alter_aggregatefilter_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatefilter',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='admin_analytics.aggregatecard'),
        ),
    ]
