# Generated by Django 3.2.9 on 2022-04-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0007_alter_aggregatefilter_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatefilter',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_filters', to='admin_analytics.aggregatecard'),
        ),
        migrations.CreateModel(
            name='ModelFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_filters', to='admin_analytics.aggregatecard')),
            ],
        ),
    ]
