# Generated by Django 3.2.9 on 2022-04-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0008_auto_20220415_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatecard',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
