# Generated by Django 3.2.9 on 2022-04-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('admin_analytics', '0009_aggregatecard_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatefilter',
            name='card',
        ),
        migrations.RemoveField(
            model_name='modelfilter',
            name='card',
        ),
        migrations.AddField(
            model_name='aggregatefilter',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'admin_analytics'), ('model', 'Card')), models.Q(('app_label', 'admin_analytics'), ('model', 'Chart')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_filters', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregatefilter',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelfilter',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(models.Q(('app_label', 'admin_analytics'), ('model', 'Card')), models.Q(('app_label', 'admin_analytics'), ('model', 'Chart')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='model_filters', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelfilter',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aggregatecard',
            name='aggrigate_function',
            field=models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('min', 'Min'), ('max', 'Max'), ('avg', 'Avg')], max_length=100),
        ),
    ]
