# Generated by Django 3.2.9 on 2022-04-16 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('admin_analytics', '0010_auto_20220416_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('label', models.CharField(max_length=100)),
                ('aggrigate_function', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('min', 'Min'), ('max', 'Max'), ('avg', 'Avg')], max_length=100)),
                ('aggregate_field', models.CharField(blank=True, default='pk', max_length=100)),
                ('order_by', models.CharField(blank=True, default='pk', help_text='Default is pk.', max_length=100)),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
