# Generated by Django 3.2.9 on 2022-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0011_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart',
            field=models.CharField(choices=[('pie', 'Pie'), ('line', 'Line'), ('area', 'Area'), ('bar', 'Bar'), ('scatter', 'Scatter'), ('polar', 'Polar'), ('bubble', 'Bubble')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
