# Generated by Django 3.2.9 on 2022-04-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0012_chart_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='chart',
            new_name='type',
        ),
    ]
