# Generated by Django 3.2.9 on 2022-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_analytics', '0013_rename_chart_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(choices=[('pie', 'Pie'), ('line', 'Line'), ('area', 'Area'), ('bar', 'Bar'), ('scatter', 'Scatter'), ('polar', 'Polar'), ('bubble', 'Bubble'), ('doughnut', 'Doughnut')], max_length=100),
        ),
    ]
